name: build push and deploy image

on:
  push:
    branches: [ main]
  pull_request:
    branches: [main]


env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }}

jobs:
  build:
    runs -on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: Aws login creds config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: login to ecr 2
        uses: aws-actions/amazon-ecr-login@v1